Changes to Menu Item Spacing
jordanbaird/Ice pull request #305
Opened 2024-08-08 23:46 UTC by stonerl

- Instead of killing apps we terminate() them gracefully. Only if they do not terminate within 3 second, we forceTerminate() them.
- Disable buttons while restarting apps
- Draw progress circle
- Make Ice settings window always stay on top

2024-08-09 06:20 UTC, jordanbaird requested changes
Great PR! This should make the spacing feature a lot more robust. If you can make the suggested changes, this should be ready to merge.

2024-08-09 06:20 UTC, jordanbaird commented on Ice/Settings/SettingsWindow.swift
> +}
```suggestion
```

2024-08-09 06:20 UTC, jordanbaird commented on Ice/Settings/SettingsWindow.swift
> +                })
We have a custom modifier, `View.readWindow(onChange:)`, so let's use that here instead.

```suggestion
                .readWindow { window in
                    window.level = .floating
                }
```

2024-08-09 06:20 UTC, jordanbaird commented on Ice/Settings/SettingsPanes/GeneralSettingsPane.swift
> +            Section { spacingOptions }
Let's keep the original formatting here.

```suggestion
            Section {
                launchAtLogin
            }
            Section {
                iceIconOptions
            }
            Section {
                useIceBar
            }
            Section {
                showOnClick
                showOnHover
                showOnScroll
            }
            Section {
                autoRehideOptions
            }
            Section {
                spacingOptions
            }
```

2024-08-09 09:02 UTC, stonerl commented
Should be good now.

2024-08-09 09:08 UTC, jordanbaird requested changes
Getting some build errors and warnings involving concurrency. Can you resolve those?

2024-08-09 09:12 UTC, stonerl commented
Did you pull the latest commit? I had to force push.

2024-08-09 09:20 UTC, jordanbaird commented
Yes. These are all in MenuBarItemSpacingManager.swift. I'm using Xcode 15.4 on macOS 14.6.1.

![CleanShot 2024-08-09 at 03 19 27@2x](https://github.com/user-attachments/assets/5e29bcd3-405d-4d1e-b8ad-11563903efab)

2024-08-09 09:25 UTC, stonerl commented
Hmm. I'm using Xcode 16 beta 5 on macOS 15 beta 5.

That could be the reason why I don't get these errors…

2024-08-09 10:53 UTC, jordanbaird commented
That would be my assumption. Could be either a compiler regression, or it could be that these errors are false positives and the latest compiler fixed them. Either way, we have to make sure it builds with the latest stable Xcode release. I can fix the errors if you want, or I'm good to wait if you would prefer to.

2024-08-09 11:12 UTC, stonerl commented
I think it is faster if you fix them. Xcode 15 does not run on macOS 15 and I would have to set up a macOS 14.6 VM in order to do so myself.

2024-08-09 22:39 UTC, jordanbaird commented
Want to make sure it builds and works correctly on your machine with the changes I made?

2024-08-10 02:21 UTC, jordanbaird approved these changes

2024-08-10 08:39 UTC, stonerl commented
works

2024-08-10 08:54 UTC, merged